// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace VuVanDuc2022483.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    [Migration("20220328005124_Creat_Table_person")]
    partial class Creat_Table_person
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("VuVanDuc2022483.Models.Person", b =>
                {
                    b.Property<string>("PersonId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("VuVanDuc2022483.Models.VVD0483", b =>
                {
                    b.Property<string>("VVDId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("VVDGender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VVDName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("VVDId");

                    b.ToTable("VVD0483");
                });
#pragma warning restore 612, 618
        }
    }
}
